# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d121e6acb96525cdf31ced22ae099f8a694a7d73f6cd39832db120cd1fbe6805de2b13b255fd43a66c237faf552c6f5b85b74704894fb84dff6c001232b8f0f4

test:
  secret_key_base: 984c2b987712f685ba30f0ebc519b9b2490437510b703769b6c61a12e5352e627bcf2b65aa782c569fc5d6bef2ae59a7686e563aeaaa6b3e12e5ed4a018cb44c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
