# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 792ef9140e24b0571d5f8fbe3ab12769d118ef5cd2d80fe6f3c756c003ddcd20eb28e3cf38fef2da9589b068e46a6d1fe986c1a5ca364093e2049dde6d578c81

test:
  secret_key_base: feb08bfc9728bd82f9c14e3f3893f75d9756a26fe106b513a1aa921973bf35579dbe50835f66598f3773054a39a2d6bf6a516a07ffe778c45ff416a968fa3ea2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
