# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 868c85b907eab9635513803ddafdc6c8eae190a3c07a494ef90405b2cb63bafeb790e0ffb330b547c6150c28365673344b6140eb124276897a081252a37d24cd

test:
  secret_key_base: 821ba22b2da0e9f38c350b59cee682d6e1dfa1d4896d787f09dfe50f7c231f5b6b7d5ce86187737e4b05cf2a2babfdf81a11448d001431d7f805cd6a57b12c86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
